spring.application.name=tournament
server.port=${APP_PORT:8080}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tournament}
spring.datasource.username=${DB_USERNAME:tournament}
spring.datasource.password=${DB_PASSWORD:tournament_local}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
