ALTER TABLE tournaments
    ADD COLUMN total_games SMALLINT CHECK (total_games > 0),
    ADD COLUMN points_per_kill SMALLINT NOT NULL DEFAULT 1 CHECK (points_per_kill >= 0);

ALTER TABLE tournaments
    ADD CONSTRAINT chk_tournaments_total_games
    CHECK ((format = 'POINTS') = (total_games IS NOT NULL));


CREATE TABLE tournament_placement_points (
    tournament_id BIGINT NOT NULL REFERENCES tournaments (id) ON DELETE CASCADE,
    placement SMALLINT NOT NULL CHECK (placement >= 1),
    points SMALLINT NOT NULL CHECK (points >= 0),
    PRIMARY KEY (tournament_id, placement)
);


CREATE TABLE free_fire_games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT NOT NULL REFERENCES tournaments (id) ON DELETE CASCADE,
    game_number SMALLINT NOT NULL CHECK (game_number >= 1),
    scheduled_at TIMESTAMP,
    status VARCHAR(30) NOT NULL DEFAULT 'SCHEDULED'
           CHECK (status IN ('SCHEDULED', 'COMPLETED')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_ff_games_number
        UNIQUE (tournament_id, game_number),

    CONSTRAINT uq_ff_games_id_tournament
        UNIQUE (id, tournament_id)
);

CREATE INDEX idx_ff_games_scheduled
    ON free_fire_games (scheduled_at);


CREATE TABLE free_fire_game_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    tournament_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    placement SMALLINT NOT NULL CHECK (placement >= 1),
    kills SMALLINT NOT NULL CHECK (kills >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_ffr_game
        FOREIGN KEY (game_id, tournament_id)
        REFERENCES free_fire_games (id, tournament_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_ffr_participant
        FOREIGN KEY (tournament_id, team_id)
        REFERENCES tournament_teams (tournament_id, team_id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_ffr_team
        UNIQUE (game_id, team_id),

    CONSTRAINT uq_ffr_placement
        UNIQUE (game_id, placement)
);

CREATE INDEX idx_ffr_tournament_team
    ON free_fire_game_results (tournament_id, team_id);