CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT NOT NULL,
    team_a_id BIGINT,
    team_b_id BIGINT,
    round_number INT NOT NULL,
    match_number INT NOT NULL,
    next_match_id BIGINT,
    scheduled_at TIMESTAMP,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_matches_tournament
        FOREIGN KEY (tournament_id)
        REFERENCES tournaments(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_matches_team_a
        FOREIGN KEY (team_a_id)
        REFERENCES teams(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_matches_team_b
        FOREIGN KEY (team_b_id)
        REFERENCES teams(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_matches_next_match
        FOREIGN KEY (next_match_id)
        REFERENCES matches(id)
        ON DELETE SET NULL,

    CONSTRAINT chk_matches_different_teams
        CHECK (
            team_a_id IS NULL
            OR team_b_id IS NULL
            OR team_a_id <> team_b_id
        ),

    CONSTRAINT chk_matches_round_number
        CHECK (round_number >= 1),

    CONSTRAINT chk_matches_match_number
        CHECK (match_number >= 1),

    CONSTRAINT uq_matches_tournament_round_number
        UNIQUE (tournament_id, round_number, match_number)
);

CREATE INDEX idx_matches_tournament_id
ON matches(tournament_id);

CREATE INDEX idx_matches_team_a_id
ON matches(team_a_id);

CREATE INDEX idx_matches_team_b_id
ON matches(team_b_id);

CREATE INDEX idx_matches_next_match_id
ON matches(next_match_id);

CREATE INDEX idx_matches_scheduled_at
ON matches(scheduled_at);