CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    min_players INT CHECK (min_players > 0),
    logo_url VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO games (code, name, min_players) VALUES
    ('ROV', 'ROV', 5),
    ('FREE_FIRE', 'Free Fire', 4),
    ('VALORANT', 'Valorant', 5),
    ('FIGHTING_GAME', 'Fighting Game', 1);

ALTER TABLE teams
    ADD COLUMN game_id BIGINT REFERENCES games (id) ON DELETE RESTRICT,
    ADD COLUMN logo_url VARCHAR(500);

CREATE INDEX idx_teams_game ON teams (game_id);

ALTER TABLE tournaments
    ADD COLUMN game_id BIGINT REFERENCES games (id) ON DELETE RESTRICT,
    ADD COLUMN format VARCHAR(30) NOT NULL DEFAULT 'SINGLE_ELIMINATION'
        CHECK (format IN ('SINGLE_ELIMINATION', 'POINTS')),
    ADD COLUMN logo_url VARCHAR(500);

CREATE INDEX idx_tournaments_game_start
    ON tournaments (game_id, start_date);